#!/usr/bin/env python3
"""
6-voltaire
This module prints the correct answer for the multiple-choice question:
    d/dx [ln(x^2)]
    
The available options are:
    1. 2/x
    2. 1/x^2
    3. do this
    4. 1/x

Since the derivative of ln(x^2) is 2/x, the correct answer is option 1.
"""

def main():
    """
    Prints the correct multiple-choice answer.
    """
    print("1")


if __name__ == "__main__":
    main()
